### ISSUE TITLE
Unable to install...

### ISSUE THREAD

**Issue by conqueror8888** [internxt/drive-server#230]
Attempting to install on Ubuntu 20.04 LTS and encountered the following:

root@apex:~/drive-server# yarn
yarn install v1.22.17
[1/5] Validating package.json...
error drive-server@1.1.0: The engine "node" is incompatible with this module. Expected version ">=14.17". Got "10.24.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

root@apex:~/drive-server# node -v
v10.24.1

root@apex:~/drive-server# yarn upgrade
yarn upgrade v1.22.17
error An unexpected error occurred: "https://npm.pkg.github.com/@internxt%2finxt-js: npm package \"inxt-js\" does not exist under owner \"internxt\"".
info If you think this is a bug, please open a bug report with the information provided in "/root/drive-server/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
[yarn-error.log](https://github.com/internxt/drive-server/files/8304524/yarn-error.log)

yarn-error.log is attached here.

**Comment by conqueror8888** [comment]
Can anybody shed some light on this issue, please? Been stuck here for a while now.

**Comment by conqueror8888** [comment]
Appreciate your response. Any quick fix to allow the setup to complete at all? Or better for Q3 release?

**Comment by ChocoPie02** [comment]
> Appreciate your response. Any quick fix to allow the setup to complete at all? Or better wait for Q3 release?

you need to use node up above 14.17 to install on 1/5 step

but after that i encounter some issue, that Dependencies are missing or 404 not found
here my console log 

````

> PS D:\internxt> yarn install
> yarn install v1.22.18
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> error An unexpected error occurred: "https://npm.pkg.github.com/download/@internxt/inxt-js/1.3.0/89a47918aa512d08227637eaddc0941c31b3aa9653d2e3639f15785d47c99008: Request failed \"404 Not Found\"".
> info If you think this is a bug, please open a bug report with the information provided in "D:\\internxt\\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command

[yarn-error.log](https://github.com/internxt/drive-server/files/8386093/yarn-error.log)
