### ISSUE TITLE
The exact same issues every time 

### ISSUE THREAD

**Issue by RajrupDasid** [internxt/drive-server#381]
Every time on your site when ever i try to download files it's stuck either on 73% decrypting or 100% decrypting 
or did not download the full file like if it's 100MB file its downloaded only like 56 MB or so the shows completed 
when i try to access it it shows file error or corrupted 

why? 
it's  absolutely frustrating  and painful to use this service and website. 
every time same issue every time same bug , 
and this site does not work on firefox only works on chrome.
so i have to change my browser every time to access this site.
what should i do?
when you gonna fix this man?

**Comment by RasheedAZ** [comment]
Working for me on Firefox. Tested with 200 MB file. No issues except low speed < 1Mbs

**Comment by RajrupDasid** [comment]
I already leave Internxt due to this issue 6 months ago. and I don't want to go back
